# Generated by Django 5.2.5 on 2026-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('Preinscripto', 'Preinscripto'), ('Inscripto', 'Inscripto'), ('Baja', 'Baja')], default='Preinscripto', max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
