# Generated by Django 5.2.5 on 2026-08-21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_alter_alumno_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 8, 21), verbose_name='Fecha de inscripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='pabellon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pabellón'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], default='Mañana', max_length=20, null=True, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso / División'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='situacion_laboral',
            field=models.CharField(blank=True, choices=[('Trabaja', 'Trabaja'), ('No trabaja', 'No trabaja'), ('Estudia y trabaja', 'Estudia y trabaja')], default='No trabaja', max_length=30, null=True, verbose_name='Situación laboral'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estudios_primarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Estudios primarios'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estudios_secundarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Estudios secundarios'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentacion/', verbose_name='Documentación escaneada'),
        ),
    ]
