# Generated by Django 6.1 on 2026-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_add_new_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='continuidad_estudios',
            field=models.CharField(blank=True, choices=[('Continúa', 'Continúa'), ('Interrumpió', 'Interrumpió'), ('Reincorporado', 'Reincorporado')], default='Continúa', max_length=30, null=True, verbose_name='Continuidad de estudios'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='recupero_libertad',
            field=models.BooleanField(default=False, verbose_name='Recuperó la libertad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='situacion_academica',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Pendiente', 'Pendiente'), ('Egresado', 'Egresado')], default='Regular', max_length=30, null=True, verbose_name='Situación académica'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='unidad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Unidad / institución'),
        ),
    ]
